### ISSUE TITLE
Timeline CSV (parse_csv) does not work with commas in data

### ISSUE THREAD

**Issue by keithjjones** [Rurik/Noriben#10]
parse_csv does not take into account the commas that could be in data.  Perhaps switching to csv.writer after outputting the data as a list of fields for each row would take care of this issue easily.

**Comment by Rurik** [comment]
Thanks! Good issue, and one that I had not expected. I will look into it.

**Comment by keithjjones** [comment]
Cool.  It shouldn't be too hard if you save a list of lists coming out of that function.  Each of the second dimension is a field in the CSV.  Just feed each list of lists into CSV writer and it takes care of the hard work for you.  I would have added some code and pull requested but I got swamped at work this week.  

For my next grad school class project I've been considering making some flow graphs out of procmon (and Noriben) CSV output so when I was playing with it I found the timeline had a variable number of fields and it wouldn't parse in correctly with pandas (which is something else you could try).

Here are a couple of projects I used CSV writer for:

https://github.com/keithjjones/hostintel
https://github.com/keithjjones/fileintel

Feel free to open those up and check out how I used CSV data.

Thanks!

**Comment by Rurik** [comment]
Long overdue but implemented in the new 1.8.0. Thanks!
