### ISSUE TITLE
Python "requests" module mussing, ProcMon cannot open pml file for reading and CSV file cannot be created.

### ISSUE THREAD

**Issue by mikenav777** [Rurik/Noriben#14]
This is the first time that I use Noriben, I followed the steps that the comments mention on the script file, and I pretty sure that I'm using the correct syntax for the command execution for the malware testing.
The first error comes when I simple run the "Noriben.py" script, the others when I put some malware samples to work. 
Anyone knows what's the cause of these issues and how to correct them?
I'll appreciate it so much. 
PD: I'm using Flare VM distribution for malware analysis. 

![malware lab - windows-2017-12-16-18-46-46](https://user-images.githubusercontent.com/34612416/34075677-07de43d6-e293-11e7-8262-8c3ce7129db5.png)
![malware lab - windows-2017-12-16-18-53-04](https://user-images.githubusercontent.com/34612416/34075678-07fe44b0-e293-11e7-83ac-10249846e9cc.png)

**Comment by Rurik** [comment]
I'm sorry that you're running across this error.

The 'requests' module is completely optional; it's only needed if you want to enable VirusTotal access. I will soon update that message to clarify, but I wouldn't be concerned over that.

The other is an unusual error with Process Monitor. I've seen similar where ProcMon didn't have write privileges, such as if the folder was removed or the command didn't have Administrator privileges. However, it looks like you are running as Admin. 

It's running under Desktop\Analysis\... but is saving to Desktop\NoribenResults\...  Did you specify this folder within the script as "output_dir"? Does the folder exist as you're running it. This could be an issue where that folder is manually saved, not in Noriben, but in the ProcMon configuration. If so, it may require running ProcMon by itself, resetting the folder to a known good one, then saving the configuration and making a new snapshot.

Please let me know what you find.

**Comment by mikenav777** [comment]
Nevermind, I solved it minutes later by just putting the ProcMon in the Same Folder as the Noriben content, all together and it worked very nicely, this tools makes a pretty decent job for behavior analysis and reporting, the CSV file stuff saves tons of time and work.

Anyway, thanks for the reply. 
Just one last doubt, does Noriben Isolates the malware for execution? If not, it would be great to add this feature, if yes, It will be my favorite and loved  tool for quick deployment when it comes to automated malware analysis.

**Comment by Rurik** [comment]
That's great news, thanks!

What do you mean exactly by isolation? Like prevent network access?

**Comment by mikenav777** [comment]
Kickass tool btw. 
Well, that could be a good feature, but by isolation I mean that the malware actually runs on a safe environment or on it's "own bubble" (something like Sandboxie file execution), for a quicker deployement.

**Comment by Rurik** [comment]
Sorry for the delay; holidays.

Thanks! So, it doesn't really run in isolation, or a jailed root. It possibly could, and it's actually been an item that I've been looking at of making a mkvirtualenv instance for it. It would take some looking into to determine if possible, and best way of doing it. So, sorry that I don't have a direct answer.
