### ISSUE TITLE
virtualbox integration

### ISSUE THREAD

**Issue by d4n13l4** [Rurik/Noriben#16]
Hi
I wanted to check if you have noriben working for virtualbox.
I was using noriben.py but then I found the videos with .sh file but I only have 32bit machines so vmware is not an option. I guess is more complete to run noribensandbox file than just noriben.py right?

Thanks

**Comment by Rurik** [comment]
Hi, sorry for the delay!

I haven't done much testing for VirtualBox, but am actively looking for someone who could help fork the NoribenSandbox.py for VBox. 

NoribenSandbox.sh and NoribenSandbox.py are very similar with the .sh being the older version that is not supported. Both are specific to VMware though. I ran into issues getting "guestcontrol copyto" to work on VBox and did not continue develop for it. It is on my roadmap for the future to have that, but it is currently not available.
