### ISSUE TITLE
Error: A file was not found

### ISSUE THREAD

**Issue by guilhermebasalia** [Rurik/Noriben#19]
Good night
I adapted the code to linux environment but I am having the following error. 

Error: A file was not found

Follows the code of the script.

#!/bin/bash

DELAY=90
WINDOWSDELAY=20
VMRUN="/usr/bin/vmrun"
FW="/media/Fw/Fw.vmx"
FW_SNAPSHOT="Fw"
VMX="/media/SandBox/SandBox.vmx"
VM_SNAPSHOT="SandBox"
VM_USER=Administrador
VM_PASS=Box1001
NORIBEN_PATH="C:\Tools\Noriben\Noriben.py"
PYTHON_PATH="C:\Python27\Python.exe"
ZIP_PATH="C:\Tools\Noriben\zip.exe"
LOG_PATH="C:\\Tools\\Noriben\\Reports"
REPORT_PATH="C:\\Tools\\Noriben\\Reports\\NoribenReports.zip"

MALWAREFILE=$1
MALWARE_PATH="C:\Sample\Sample.exe"

if [ ! -f "$1" ] 
then
 echo "Please provide executable filename as an argument."
 echo "For example:"
 echo "$0 ~/malware/ef8188aa1dfa2ab07af527bab6c8baf7"
 exit
fi

FILENAME=$(basename $MALWAREFILE)

##Firewall
"$VMRUN" -T vmware revertToSnapshot "$FW" $FW_SNAPSHOT
"$VMRUN" -T vmware start "$FW"

sleep 60

##SANDBOX
"$VMRUN" -T vmware revertToSnapshot "$VMX" $VM_SNAPSHOT
"$VMRUN" -T vmware start "$VMX"
"$VMRUN" -T vmware -gu $VM_USER  -gp $VM_PASS copyFileFromHostToGuest "$VMX" "$MALWAREFILE" "$MALWARE_PATH"

sleep $WINDOWSDELAY

"$VMRUN" -T vmware -gu $VM_USER -gp $VM_PASS runProgramInGuest "$VMX" "$PYTHON_PATH" "$NORIBEN_PATH" -d -t $DELAY --cmd "$MALWARE_PATH" --output "$LOG_PATH"
if [ $? -gt 0 ]; then
    echo "[!] File did not execute in VM correctly."
    exit
fi

"$VMRUN" -T vmware -gu $VM_USER -gp $VM_PASS runProgramInGuest "$VMX" "$ZIP_PATH" -j "$REPORT_PATH" "$LOG_PATH\\*.*"
if [ $? -eq 12 ]; then
    echo "[!] ERROR: No files found in Noriben output folder to ZIP."
    exit
fi

"$VMRUN" -T vmware -gu $VM_USER -gp $VM_PASS copyFileFromGuestToHost "$VMX" "$REPORT_PATH" /reports/Report_$FILENAME.zip

"$VMRUN" -T vmware revertToSnapshot "$VMX" $VM_SNAPSHOT

##FIREWALL
"$VMRUN" -T vmware revertToSnapshot "$FW" $FW_SNAPSHOT

**Comment by Rurik** [comment]
I'm not sure I'll be able to troubleshoot. Is it possible to determine where that error occurs?

The bash script I have is semi-deprecated due to its replacement by NoribenSandbox.py. Maybe that can be useful for what you're doing?
