### ISSUE TITLE
[!] Error trying to copy file from guest. Continuing. Error 0xff: Unexpected Error

### ISSUE THREAD

**Issue by malwarehuntingisfun** [Rurik/Noriben#25]
On my MAC OSx I used the following command:
`python /Users/malware/Desktop/noriben/Noriben-master/NoribenSandbox.py --update --screenshot -t 45 -f ./calc.exe `

The file is able to go to the Win7 machine, and perform the analysis I see the logs in the "C:\Noriben_Logs" folder, but it is it no reporting back to my MAC. I see the following error:
"[!] Error trying to copy file from guest. Continuing. Error 0xff: Unexpected Error"

Here is a part of my of my config:
```
vmrun_os = {'windows': os.path.expanduser(r'C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe'),
            'mac': os.path.expanduser(r'/Applications/VMware Fusion.app/Contents/Library/vmrun')}
debug = False
timeout_seconds = 300
#VMX = r'E:\VMs\Windows.vmwarevm\Windows.vmx'
VMX = os.path.expanduser(r'/Volumes/1TB SSD/VMs/Windows 7 (64)/Windows 7 x64.vmwarevm/Windows 7 x64.vmx')
VMRUN = vmrun_os['mac']
VM_SNAPSHOT = 'RN1'
VM_USER = 'admin'
VM_PASS = 'password'
#noriben_path = 'C:\\\\Users\\\\{}\\\\Desktop'.format(VM_USER)
#noriben_path on my WIN7 Machine:
noriben_path = 'C:\\\\Users\\\\admin\\\\Desktop\\\\Noriben'.format(VM_USER)
guest_noriben_path = '{}\\\\Noriben.py'.format(noriben_path)
procmon_config_path = '{}\\\\ProcmonConfiguration.pmc'.format(noriben_path)
report_path_structure = '{}/{}_NoribenReport.zip'  # (host_malware_path, host_malware_name_base)
host_screenshot_path_structure = '{}/{}.png'  # (host_malware_path, host_malware_name_base)
guest_log_path = 'C:\\\\Noriben_Logs'
guest_zip_path = 'C:\\\\Program Files\\\\VMware\\\\VMware Tools\\\\zip.exe'
guest_temp_zip = 'C:\\\\NoribenReports.zip'
#guest_python_path = 'C:\\\\Python27\\\\python.exe'
#guest_python_path Python 3.7 Path:
guest_python_path = 'C:\\\\Users\\\\admin\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python37\\\\python.exe'
host_noriben_path = os.path.join(os.path.dirname(os.path.abspath(sys.argv[0])), 'Noriben.py')
#guest_malware_path the following folder "c:\Malware\malware_" was created on the Windows 7 Machine
guest_malware_path = 'C:\\\\Malware\\\\malware_'
error_tolerance = 5
dontrun = False

```

**Comment by Rurik** [comment]
Did this happen just once in multiple runs, or does it appear everytime you execute?

If the former, the unfortunate part of error 0xff is that it falls in the category of "unknown VMware issue". When running at scale, VMware vmrun can be very unstable.

If the latter, can you run with the "-d" for debug mode and review the commands. The very last vmrun command that gives the error should be shown. You can copy/paste that directly onto the command line to see if the values are correct.

**Comment by malwarehuntingisfun** [comment]
Here is the output with the "-d" flag

```
Pro:Dropper malware$ python /Users/malware/Desktop/noriben/Noriben-master/NoribenSandbox.py  -d -f 'calc.exe' 
[*] Processing: calc.exe

"/Applications/VMware Fusion.app/Contents/Library/vmrun" -T ws revertToSnapshot "/Volumes/1TB SSD/VMs/06 - Windows 7 (64)/Windows 7 x64.vmwarevm/Windows 7 x64.vmx" "NR5"

"/Applications/VMware Fusion.app/Contents/Library/vmrun" -T ws start "/Volumes/1TB SSD/VMs/06 - Windows 7 (64)/Windows 7 x64.vmwarevm/Windows 7 x64.vmx"

"/Applications/VMware Fusion.app/Contents/Library/vmrun" -gu admin -gp password copyFileFromHostToGuest "/Volumes/1TB SSD/VMs/06 - Windows 7 (64)/Windows 7 x64.vmwarevm/Windows 7 x64.vmx" "calc.exe" "C:\\Malware\\malware_calc.exe"

"/Applications/VMware Fusion.app/Contents/Library/vmrun" -T ws -gu admin -gp password runProgramInGuest "/Volumes/1TB SSD/VMs/06 - Windows 7 (64)/Windows 7 x64.vmwarevm/Windows 7 x64.vmx" -activeWindow -interactive C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python37\\python.exe "C:\\Users\\admin\\Desktop\\Noriben-master\\Noriben.py" -t 30 --headless --output "C:\\Noriben_Logs"  --cmd C:\\Malware\\malware_calc.exe  -d

"/Applications/VMware Fusion.app/Contents/Library/vmrun" -T ws -gu admin -gp password runProgramInGuest "/Volumes/1TB SSD/VMs/06 - Windows 7 (64)/Windows 7 x64.vmwarevm/Windows 7 x64.vmx" -activeWindow -interactive "C:\\Program Files\\VMware\\VMware Tools\\zip.exe" -j C:\\NoribenReports.zip "C:\\Noriben_Logs\\*.*"

"/Applications/VMware Fusion.app/Contents/Library/vmrun" -gu admin -gp password copyFileFromGuestToHost "/Volumes/1TB SSD/VMs/06 - Windows 7 (64)/Windows 7 x64.vmwarevm/Windows 7 x64.vmx" C:\\NoribenReports.zip "./calc_NoribenReport.zip"

Error: A file was not found

[!] Error trying to copy file from guest. Continuing. Error 0xff: Unexpected Error
```

**Comment by Rurik** [comment]
Can you confirm that those files are in the right location? C:\NoribenReports.zip, and that ./calc_NoribenReport.zip doesn't already exist.

**Comment by malwarehuntingisfun** [comment]
I don't see any zip file, but I see the reports dumped in the "C:\Noriben_Logs" folder
(screen shots attached)
![Screen Shot 2019-03-24 at 12 14 41 PM](https://user-images.githubusercontent.com/48774777/54882263-92cecf80-4e2e-11e9-9033-08a6268c8289.png)
![Screen Shot 2019-03-24 at 12 14 20 PM](https://user-images.githubusercontent.com/48774777/54882264-92cecf80-4e2e-11e9-9e25-e2ffb6c7dd0d.png)

**Comment by malwarehuntingisfun** [comment]
Also I wanted to confirm that "**C:\Program Files\VMware\VMware Tools\zip.exe**" does Exist on the virtual machine.

**Comment by Rurik** [comment]
It sounds like the zip just isn't being created.

While the VM is running, just as it is, manually run that command on the host:

`"/Applications/VMware Fusion.app/Contents/Library/vmrun" -T ws -gu admin -gp password runProgramInGuest "/Volumes/1TB SSD/VMs/06 - Windows 7 (64)/Windows 7 x64.vmwarevm/Windows 7 x64.vmx" -activeWindow -interactive "C:\\Program Files\\VMware\\VMware Tools\\zip.exe" -j C:\\NoribenReports.zip "C:\\Noriben_Logs\\*.*"`

I should add a check to ensure the ZIP exists before copying it off, but very likely that zip is failing.

**Comment by malwarehuntingisfun** [comment]
The command does start the deflating process (see screenshot), but there is NO zip file on the C:\ drive.  

While the VM was on I manually put the command 

`zip.exe -j C:\NoribenReports.zip "C:\Noriben_Logs\*.*"`

in  the command prompt, and it did the same thing by deflating the files, but NO zip file

`C:\Program Files\VMware\VMware Tools>zip.exe -j C:\NoribenReports.zip "C:\Noriben_Logs\*.*"
updating: Noriben_24_Mar_19__22_03_403719.csv (172 bytes security) (deflated 95%)
updating: Noriben_24_Mar_19__22_03_403719.log (172 bytes security) (deflated 60%)
updating: Noriben_24_Mar_19__22_03_403719.pml (160 bytes security) (deflated 89%)
updating: Noriben_24_Mar_19__22_03_403719.txt (172 bytes security) (deflated 77%)
updating: Noriben_24_Mar_19__22_03_403719_timeline.csv (172 bytes security) (deflated 82%)`

**HOWEVER** when I opened up command prompt with "_Run as administrator_" and ran the same command a "zip" file was created on the drive.  It looks like its a privilege issues.  Any thoughts?

![Screen Shot 2019-03-24 at 3 09 54 PM](https://user-images.githubusercontent.com/48774777/54884428-5bb8e800-4e47-11e9-8376-c7fdc5478f0f.png)

**Comment by Rurik** [comment]
You are correct, and this was an issue that I had not perceived. Yes, there could be admin rights issues to root. My takeaway is that it should not be C:\.

Could you try with setting:

 ```
guest_temp_zip = 'C:\\\\Noriben_Logs\\\\NoribenReports.zip'
```

That *should* fix it and, if so, I will make similar fix to the code.

**Comment by malwarehuntingisfun** [comment]
Resolved!!!  So the  **"guest_temp_zip="** must be pointed outside the "C:\" for permission issues.  
Solution: 
`guest_temp_zip = 'C:\\\\Noriben_Logs\\\\NoribenReports.zip'`

**Comment by malwarehuntingisfun** [comment]
Solved

**Comment by Rurik** [comment]
Brilliant! Thank you for notifying me.
