### ISSUE TITLE
Shutting down VM after analysis

### ISSUE THREAD

**Issue by malwarehuntingisfun** [Rurik/Noriben#26]
After the analysis the virtual machine does not shut down, can the python code be updated to send the "**vmrun stop**", and possibly make that a variable where the user can define after how many seconds to initiate the "vmrun stop" command.

Also, I don't mind being a Ginnie pig for any of the code testing!

**Comment by Rurik** [comment]
This is a good idea. I'll play with the concept this weekend.

**Comment by Rurik** [comment]
This has been implemented into NoribenSandbox 1.3.

It now has `--shutdown` and `--suspend` options to shutdown or pause the system after execution.

Please feel free to reopen this Issue if they do not work for you.
