### ISSUE TITLE
Procmon needs permisison to "make changes on this computer"

### ISSUE THREAD

**Issue by malwarehuntingisfun** [Rurik/Noriben#27]
![Screen Shot 2019-03-24 at 5 20 44 PM](https://user-images.githubusercontent.com/48774777/54886161-23230980-4e5b-11e9-8b0f-ed0bfd6ca709.png)

After the file is sent to the virtual machine Windows requires the user to accept "yes" for procmon to initiate.  I tried going to "User account control settings” and selecting "never" notify, but that does not resolve the issue.  Any thoughts?

**Comment by Rurik** [comment]
Apologies for the delay. This is something that I won't have control over changing, nor something that I've seen locally. Disabling UAC *should* fix this and I'm not sure why it isn't.

Does your local user have admin privileges?
