### ISSUE TITLE
How to whitelist System:4 process?

### ISSUE THREAD

**Issue by juliaebner** [Rurik/Noriben#31]
I can add any processes to the whitelist (I normally just use the global one), but how do I add the process System:4 specifically? I wasn't able to use "System:4" in the normal regex and can't see how to include the specific process number (4) otherwise.

**Comment by Rurik** [comment]
Thanks! This should be something that's possible but I'll have to do some testing to check. And, if it currently can't be, get that functionality in.

**Comment by juliaebner** [comment]
Hi Rurik, I have just found a way to do it, at least for a workaround.
After line 949 (in the original file), just after "try:", I have added the following:
try:
# All lines containing System:4 will be skipped and therefore not appended to the report.
    if (field[1] == 'System' and field[2] == '4'):
        continue

**Comment by Rurik** [comment]
Thanks! My only worry is for malware that may be reflective loading and inject back into System.

There's variants of Chimera ransomware that do this. Rare, but a dramatic thing to potentially overlook. 

It may be best to exclude from procmon while it is running, before it gets to parsing the output. However, I will look into ways to optionally add it as a filter.

**Comment by juliaebner** [comment]
Thanks, that is good to know! A possibility then may be to only skip System:4 for CreateFile or CreateFolder operations.
