### ISSUE TITLE
Malware - encrypting the.pml 

### ISSUE THREAD

**Issue by oasec1** [Rurik/Noriben#33]
Malware appears to be encrypting the.pml file. I know procmon allows you to change the name of that file with the commandline option of /BackingFile can you also do that with the --f or -f and change the output log file name? I dont want to change the name just the log files extension.

Any chance this can be added as an option?

Thanks
Robert

**Comment by oasec1** [comment]
Still encountering these issue daily with  ransomware.  What are you thoughts about adding an option to just eliminate the extension altogether? Many of the samples that I've encountered don't encrypt files that don't have extensions.

**Comment by Rurik** [comment]
Closed. Ticket replaced with #42
