### ISSUE TITLE
Chinese characters in log

### ISSUE THREAD

**Issue by oasec1** [Rurik/Noriben#34]
I'm getting quite a bit of Chinese data in the Noriben texts output file in numerous places, a sample is below.

[RegSetValue] svchost.exe:8732 > \REGISTRY\A\{7b42fa3c-6aa4-0406-a1bc-87c340d8b210}\DeliveryOptimization\Swarms\4536136f0eaaffe9ee1c675547cd50b2ed0c09fe\CdnURL  =  Ðèèàt^^f\èØê\ÈØ\ÈÊØÒìÊäò\Úà\ÚÒÆäÞæÞÌè\ÆÞÚ^ÌÒØÊæèäÊÂÚÒÜÎæÊäìÒÆÊ^ÌÒØÊæ^nÌÈh`hbjZdpÌhZhÄjÄZpnÆfZ`nfÄÂÄÌpjhrp~ bzbjlpnfd`hrL dzh`dL fzdL hz`¢äbnÐêlÊ²jê¤¬fJdÌÜ¦d`hðÔbàJdÌªÄ¦¦¤ØÄÖ´bè®¤ðnâÔî¬àÐôÜîJdÌrÜÎÐèÌ¤äòªÌ¤äJfÈJfÈ

Not sure whats causing this, any idea?

Thanks
Robert

**Comment by Seductro** [comment]
Straight up this is a form of encryption that somebody is doing lately. I've deobfuscated a few and from what I can tell they are parading as legit windows processes but are actively using DLL's to control your PC through a botnet. If you are investigating malwarw you legitimately have on your PC right now, I would make sure that in your device manager your "SMBus" is using the correct driver.

**Comment by Rurik** [comment]
I apologize that I did not respond sooner, but at @Seductro mentioned, this is very likely obfuscated data. I've been told that Trickbot uses this technique. This is just binary data representation of that. 

For now Noriben doesn't have the ability to show hex-bytes for a string that could be binary; it's not that smart.
