### ISSUE TITLE
procmon.exe path problem

### ISSUE THREAD

**Issue by xrkk** [Rurik/Noriben#41]
I installed procmon.exe in directory: "C:\ProgramData\chocolatey\lib\sysinternals\tools\Procmon.exe".
After Ctrl+C to terminate Noriben.py, 2 message boxes pop up, indicating "Unable to open xxx.pml for reading" and "The file was not saved.: There are no items to be saved."
But if I place a copy of procmon.exe in the same directory with Noriben.py, everything works just fine.
After some digging, I thought the problem happens when using procmon.exe to convert pml to csv file, some relative path stuff...
I'd prefer to not place a copy of procmon.exe in the Noriben.py directory, so that I can automatically update procmon.exe when new releases arrives.

**Comment by Rurik** [comment]
Thank you for letting me know.

I'll do some testing on this to see if I can find the exact problem.

**Comment by Rurik** [comment]
Apologies for the lengthy delay. In testing this now, I've had issues duplicating. Procmon.exe doesn't exist in the same folder as Noriben.py in any of my testing. I assume that the chocolatey path is in your PATH statement? I've tried to replicate your environment and it's working fine.

Can you run it with the debug option (-d) and provide the logs? It should show the actual command lines being executed, which may contain the issue.

**Comment by Rurik** [comment]
Closing as no response. Please feel free to reopen and submit more information.
