### ISSUE TITLE
New issue - VM running Windows 11 Pro

### ISSUE THREAD

**Issue by oasec1** [Rurik/Noriben#56]
Here is the error that is being displayed upon execution. Python version- python-3.11.2 32bit

[*] Running cmdline: "c:\tools"\procmon.exe" /BackingFile "Noriben_20_Feb_23__11_47_843808.pml" /Quiet /Minimized /LoadConfig "c:\noriben\ProcmonConfiguration.PMC"
Traceback (most recent call last):
  File "c:\noriben\noriben.py", line 1591, in <module>
    main()
  File "c:\noriben\noriben.py", line 1524, in main
    launch_procmon_capture(procmonexe, pml_file, pmc_file)
  File "c:\noriben\noriben.py", line 976, in launch_procmon_capture
    subprocess.Popen(cmdline)
  File "C:\Users\oasec\AppData\Local\Programs\Python\Python311-32\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\oasec\AppData\Local\Programs\Python\Python311-32\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied

Once again thanks for such a great tool!
Robert

**Comment by Rurik** [comment]
That is odd. Are you able to run the command line directly as it is there? Maybe the double quotes in the procmon path are causing problems?


 "c:\tools"\procmon.exe" /BackingFile "test.pml" /Quiet /Minimized /LoadConfig "c:\noriben\ProcmonConfiguration.PMC"

**Comment by oasec1** [comment]
No it wasn't run manually from an administrator command prompt.

**Comment by oasec1** [comment]
I rebooted again, and then ran it manually It is working now so my plan is to revisit the batch files for typos.

Thanks
Robert

**Comment by Rurik** [comment]
Sounds good. I'm going to close this issue for now, but please reopen it if the problem continues.

**Comment by oasec1** [comment]
Will do thanks!
