### ISSUE TITLE
hashlist and csv creation issues

### ISSUE THREAD

**Issue by phate1** [Rurik/Noriben#58]
Hey

Just loaded this up today and hit a few snags at first.

Kept getting errors about not being able to open the PML for reading found that it was trying to read the file before the first process had fully terminated and released it. solved that on my side simply enough by adding a 30 second sleep timer to `process_pml_to_csv` maybe my VM is exceptionally slow? There is probably a better fix, but it was a quick plaster

I also had issues with adding the hash list in read_hash_file function looks like the csv reader line was updated a few months back to:
`reader = csv.DictReader(hash_file_handle)`

but later code is still expecting a list:

`hashval = hash_line[0]`

Again quick fix for me just changed it back to:

`csv.reader(hash_file_handle)`

thanks

**Comment by Rurik** [comment]
Please reopen if there is more to add. Thanks!
