### ISSUE TITLE
CLosing Noriben

### ISSUE THREAD

**Issue by oasec1** [Rurik/Noriben#61]
I just downbloaded the lstest archive and installed it. Once executed  dow whatever.... then use Ctlr to close Noriben ite hang and doesn't ever close. Even just after a few minutes of reallty just windows operating.

**Comment by oasec1** [comment]
I just downloaded the latest archive and installed it. Once executed  do whatever.... then use Ctlr to close Noriben it hangs and doesn't ever close. Even just after a few minutes of reallty just windows operating.  It finally closed.

**Comment by Rurik** [comment]
Saw this as closed. If this continued can you run -d and attach the debug log? (redact if necessary)
