### ISSUE TITLE
noriben does not create the text file

### ISSUE THREAD

**Issue by lupinlicious** [Rurik/Noriben#63]
Hello,

Noriben does not create the text file when I'm using a large binary to analyze, like 3.5GB
![noriben](https://github.com/Rurik/Noriben/assets/78304559/74c95f20-531c-4acb-9224-a0f96535151e)

**Comment by Rurik** [comment]
It may be failing somewhere between converting from CSV to TXT. Can you run it with the -d option for debug, and see what it outputs. From the size of the CSV, it will likely be a massive debug file. But the end of it should have good information. If you are able to provide the CSV, I can review as well.

**Comment by lupinlicious** [comment]
Thanks! It seems it only took an insanely long time to create the text
file. Would it be possible to speed this up?

Or perhaps add a flag to noriben.py so I can analyze an external .PML file
with noriben.py without running the executable?

Best regards
Ulf

**Comment by Rurik** [comment]
There is a --pml / -p flag to point to the PML file. There is also a --csv / -c for the CSV.

There should have been a large reduction in size from the PML to CSV. That suggests filters were not working. When you run Noriben again, maximize the Procmon window and select Filter > Filter. There should be a large amount of filters in place. If they are there, and the files are still that large, then it's just an extraordinary amount of events. If you actively monitor Procmon during execution you could see which events are occurring and filter them out during execution. That'll prevent them from going into the PML/CSV and you could set them as your own new filters (or add as suggestions for new global filters).

**Comment by Rurik** [comment]
Please reopen if there is more to add. Thanks!
