### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by kholbrook1303** [Rurik/Noriben#9]
Hello, I stumbled across this as a project I am working on is somewhat similar, and was curious if this is still actively being developed?

**Comment by oasec1** [comment]
I'm not the developer but c but use Noriben daily. Can you share what
you're working on?

**Comment by Rurik** [comment]
Yes, very much. It's reached a sort-of stable period with the next round of changes (including previous Issue) delayed until the end of summer.

**Comment by kholbrook1303** [comment]
Thanks, just curious.  I cannot divulge the content of my project, as it is tied to something I am doing for my employer, however, I have been tinkering with ProcMon for malware analysis (Having a strong background with cuckoo), and despite the obvious limitations like debugger aware malware, am working on some unique features using the procmon capture.  Specifically with execution flow mapping so you can better see the end-to-end aspect of replication with a hierarchical output structure.  Aside from that, I am typically one to share knowledge vs bottling it up, and was curious if bugs where submitted, that there was an ear on the other end to listen.

I have not really gone in depth with this code base, so I cannot say if some of my ideas are already implemented, so could even be duplicating efforts, but some cool concepts and quite possibly some useful aspects for machine controlling nonetheless!

Thanks again!

**Comment by Rurik** [comment]
One other idea to play with is ProcDOT, which does similar but is focused on visualization. While Noriben doesn't do automated execution flow management, the ability to sit in the background while debugging does perform similar.
